import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

const _kLocaleStorageKey = '__locale_key__';

class FFLocalizations {
  FFLocalizations(this.locale);

  final Locale locale;

  static FFLocalizations of(BuildContext context) =>
      Localizations.of<FFLocalizations>(context, FFLocalizations)!;

  static List<String> languages() => [
        'en',
        'fr',
        'es',
        'zh_Hans',
        'ru',
        'pt',
        'de',
        'ja',
        'it',
        'ko',
        'tr',
        'vi',
        'th',
        'id',
        'ar',
        'te',
        'hi'
      ];

  static late SharedPreferences _prefs;
  static Future initialize() async =>
      _prefs = await SharedPreferences.getInstance();
  static Future storeLocale(String locale) =>
      _prefs.setString(_kLocaleStorageKey, locale);
  static Locale? getStoredLocale() {
    final locale = _prefs.getString(_kLocaleStorageKey);
    return locale != null && locale.isNotEmpty ? createLocale(locale) : null;
  }

  String get languageCode => locale.toString();
  String? get languageShortCode =>
      _languagesWithShortCode.contains(locale.toString())
          ? '${locale.toString()}_short'
          : null;
  int get languageIndex => languages().contains(languageCode)
      ? languages().indexOf(languageCode)
      : 0;

  String getText(String key) =>
      (kTranslationsMap[key] ?? {})[locale.toString()] ?? '';

  String getVariableText({
    String? enText = '',
    String? frText = '',
    String? esText = '',
    String? zh_HansText = '',
    String? ruText = '',
    String? ptText = '',
    String? deText = '',
    String? jaText = '',
    String? itText = '',
    String? koText = '',
    String? trText = '',
    String? viText = '',
    String? thText = '',
    String? idText = '',
    String? arText = '',
    String? teText = '',
    String? hiText = '',
  }) =>
      [
        enText,
        frText,
        esText,
        zh_HansText,
        ruText,
        ptText,
        deText,
        jaText,
        itText,
        koText,
        trText,
        viText,
        thText,
        idText,
        arText,
        teText,
        hiText
      ][languageIndex] ??
      '';

  static const Set<String> _languagesWithShortCode = {
    'ar',
    'az',
    'ca',
    'cs',
    'da',
    'de',
    'dv',
    'en',
    'es',
    'et',
    'fi',
    'fr',
    'gr',
    'he',
    'hi',
    'hu',
    'it',
    'km',
    'ku',
    'mn',
    'ms',
    'no',
    'pt',
    'ro',
    'ru',
    'rw',
    'sv',
    'th',
    'uk',
    'vi',
  };
}

class FFLocalizationsDelegate extends LocalizationsDelegate<FFLocalizations> {
  const FFLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    final language = locale.toString();
    return FFLocalizations.languages().contains(
      language.endsWith('_')
          ? language.substring(0, language.length - 1)
          : language,
    );
  }

  @override
  Future<FFLocalizations> load(Locale locale) =>
      SynchronousFuture<FFLocalizations>(FFLocalizations(locale));

  @override
  bool shouldReload(FFLocalizationsDelegate old) => false;
}

Locale createLocale(String language) => language.contains('_')
    ? Locale.fromSubtags(
        languageCode: language.split('_').first,
        scriptCode: language.split('_').last,
      )
    : Locale(language);

final kTranslationsMap = <Map<String, Map<String, String>>>[
  // AskAI
  {
    'xgxr2mnz': {
      'en': 'Type Here...',
      'ar': 'أكتب هنا...',
      'de': 'Geben Sie hier ein...',
      'es': 'Escriba aquí...',
      'fr': 'Écrivez ici...',
      'hi': 'यहाँ टाइप करें...',
      'id': 'Ketik di sini...',
      'it': 'Digitare qui...',
      'ja': 'ここに入力...',
      'ko': '여기에 입력하세요...',
      'pt': 'Digite aqui...',
      'ru': 'Введите здесь...',
      'te': 'ఇక్కడ టైపు చేయండి...',
      'th': 'พิมพ์ที่นี่...',
      'tr': 'Buraya yaz...',
      'vi': 'Nhập ở đây...',
      'zh_Hans': '在此输入...',
    },
    'osy172y3': {
      'en': 'Generate',
      'ar': 'يولد',
      'de': 'Generieren',
      'es': 'Generar',
      'fr': 'Générer',
      'hi': 'उत्पन्न',
      'id': 'Menghasilkan',
      'it': 'creare',
      'ja': '生成する',
      'ko': '생성하다',
      'pt': 'Gerar',
      'ru': 'Генерировать',
      'te': 'సృష్టించు',
      'th': 'สร้าง',
      'tr': 'Oluştur',
      'vi': 'Phát ra',
      'zh_Hans': '产生',
    },
    'h99xu064': {
      'en': 'Ask AI ',
      'ar': 'اسأل الذكاء الاصطناعي',
      'de': 'Fragen Sie die KI',
      'es': 'Pregúntale a la IA',
      'fr': 'Demandez à l\'IA',
      'hi': 'एआई से पूछें',
      'id': 'Tanya AI',
      'it': 'Chiedi all\'AI',
      'ja': 'AIに聞く',
      'ko': 'AI에게 물어보세요',
      'pt': 'Pergunte à IA',
      'ru': 'Спросите ИИ',
      'te': 'AIని అడగండి',
      'th': 'ถามเอไอ',
      'tr': 'Yapay zekaya sor',
      'vi': 'Hỏi AI',
      'zh_Hans': '询问人工智能',
    },
    'jv8wi3mr': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'id': 'Rumah',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'pt': 'Lar',
      'ru': 'Дом',
      'te': 'హోమ్',
      'th': 'บ้าน',
      'tr': 'Ev',
      'vi': 'Trang chủ',
      'zh_Hans': '家',
    },
  },
  // Home
  {
    '1v31q73v': {
      'en': 'My Note/Habits',
      'ar': 'ملاحظاتي',
      'de': 'Meine Notizen',
      'es': 'Mis notas',
      'fr': 'Mes notes',
      'hi': 'मेरी टिप्पणियाँ',
      'id': 'Catatan Saya',
      'it': 'I miei appunti',
      'ja': '私のノート',
      'ko': '내 노트',
      'pt': 'Minhas anotações',
      'ru': 'Мои заметки',
      'te': 'నా గమనికలు',
      'th': 'บันทึกของฉัน',
      'tr': 'Notlarım',
      'vi': 'Ghi chú của tôi',
      'zh_Hans': '我的笔记',
    },
    'snxwjvjx': {
      'en': '5 mins ago',
      'ar': 'منذ 5 دقائق',
      'de': 'Vor 5 Minuten',
      'es': 'Hace 5 minutos',
      'fr': 'il y a 5 minutes',
      'hi': '5 मिनट पहले',
      'id': '5 menit yang lalu',
      'it': '5 minuti fa',
      'ja': '5分前',
      'ko': '5분 전',
      'pt': '5 minutos atrás',
      'ru': '5 минут назад',
      'te': '5 నిమిషాల క్రితం',
      'th': '5 นาทีที่แล้ว',
      'tr': '5 dakika önce',
      'vi': '5 phút trước',
      'zh_Hans': '5 分钟前',
    },
    'mj2idr41': {
      'en': 'Head of Design',
      'ar': 'رئيس قسم التصميم',
      'de': 'Leiter Design',
      'es': 'Jefe de Diseño',
      'fr': 'Responsable de la conception',
      'hi': 'डिज़ाइन प्रमुख',
      'id': 'Kepala Desain',
      'it': 'Responsabile della progettazione',
      'ja': '設計責任者',
      'ko': '디자인 책임자',
      'pt': 'Chefe de Design',
      'ru': 'руководитель отдела дизайна',
      'te': 'డిజైన్ హెడ్',
      'th': 'หัวหน้าฝ่ายออกแบบ',
      'tr': 'Tasarım Başkanı',
      'vi': 'Người đứng đầu thiết kế',
      'zh_Hans': '设计主管',
    },
    'ronwcidy': {
      'en': 'Donate Now',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'b8ibp1gj': {
      'en': 'Feel Free to Donate',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'g3xytgjf': {
      'en': 'Donate',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '8qf3ykdd': {
      'en': 'Get Best Book Ever',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '7jxz0lmp': {
      'en': 'Get Access',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'e93hnxy1': {
      'en': 'LogOut',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'drqmcbj6': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'id': 'Rumah',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'pt': 'Lar',
      'ru': 'Дом',
      'te': 'హోమ్',
      'th': 'บ้าน',
      'tr': 'Ev',
      'vi': 'Trang chủ',
      'zh_Hans': '家',
    },
  },
  // CutsPage
  {
    '0zbuqi70': {
      'en': 'Create Habits to be Remaindered',
      'ar': 'خلق العادات التي يجب أن تبقى',
      'de': 'Schaffen Sie Gewohnheiten, die beibehalten werden sollen',
      'es': 'Crear hábitos que se mantendrán',
      'fr': 'Créer des habitudes à conserver',
      'hi': 'शेष रहने के लिए आदतें बनाएँ',
      'id': 'Ciptakan Kebiasaan untuk Dipertahankan',
      'it': 'Crea abitudini da mantenere',
      'ja': '残したい習慣を作る',
      'ko': '남을 습관을 만들어라',
      'pt': 'Crie hábitos a serem mantidos',
      'ru': 'Создайте привычки, которые останутся в памяти',
      'te': 'రిమైండర్ చేయడానికి అలవాట్లను సృష్టించండి',
      'th': 'สร้างนิสัยให้คงอยู่',
      'tr': 'Kalıcı Olacak Alışkanlıklar Yaratın',
      'vi': 'Tạo thói quen được duy trì',
      'zh_Hans': '养成需要保持的习惯',
    },
    'dt6ok8gl': {
      'en': 'Short Description of what is going on...',
      'ar': 'وصف مختصر لما يحدث...',
      'de': 'Kurze Beschreibung dessen, was los ist...',
      'es': 'Breve descripción de lo que está pasando...',
      'fr': 'Brève description de ce qui se passe...',
      'hi': 'क्या हो रहा है इसका संक्षिप्त विवरण...',
      'id': 'Deskripsi Singkat tentang apa yang sedang terjadi...',
      'it': 'Breve descrizione di ciò che sta accadendo...',
      'ja': '何が起こっているかの簡単な説明...',
      'ko': '무슨 일이 일어나고 있는지에 대한 간단한 설명...',
      'pt': 'Breve descrição do que está acontecendo...',
      'ru': 'Краткое описание происходящего...',
      'te': 'ఏమి జరుగుతుందో సంక్షిప్త వివరణ...',
      'th': 'คำอธิบายสั้น ๆ เกี่ยวกับสิ่งที่เกิดขึ้น...',
      'tr': 'Neler olup bittiğinin kısa açıklaması...',
      'vi': 'Mô tả ngắn gọn về những gì đang xảy ra...',
      'zh_Hans': '简短描述正在发生的事情...',
    },
    '13ucgvef': {
      'en': 'Field is required...',
      'ar': 'الحقل مطلوب...',
      'de': 'Feld ist erforderlich...',
      'es': 'Se requiere campo...',
      'fr': 'Champ requis...',
      'hi': 'ये स्थान भरा जाना है...',
      'id': 'Bidang wajib diisi...',
      'it': 'Il campo è obbligatiorio...',
      'ja': 'フィールドは必須項目です...',
      'ko': '필드는 필수입니다...',
      'pt': 'Campo é obrigatório...',
      'ru': 'Поле, обязательное для заполнения...',
      'te': 'ఫీల్డ్ అవసరం...',
      'th': 'ต้องระบุข้อมูล...',
      'tr': 'Alan gereklidir...',
      'vi': 'Lĩnh vực được yêu cầu...',
      'zh_Hans': '字段为必填项...',
    },
    'xvi22cf1': {
      'en': 'More letters Required',
      'ar': 'مطلوب المزيد من الحروف',
      'de': 'Weitere Buchstaben erforderlich',
      'es': 'Más letras requeridas',
      'fr': 'Plus de lettres requises',
      'hi': 'अधिक पत्रों की आवश्यकता है',
      'id': 'Diperlukan lebih banyak surat',
      'it': 'Sono necessarie più lettere',
      'ja': 'さらに文字が必要です',
      'ko': '더 많은 글자가 필요합니다',
      'pt': 'Mais letras necessárias',
      'ru': 'Требуется больше букв',
      'te': 'మరిన్ని అక్షరాలు అవసరం',
      'th': 'ต้องมีตัวอักษรเพิ่มเติม',
      'tr': 'Daha fazla harf gerekli',
      'vi': 'Cần thêm chữ cái',
      'zh_Hans': '需要更多字母',
    },
    'qwhpxovl': {
      'en': 'Please choose an option from the dropdown',
      'ar': 'يرجى اختيار خيار من القائمة المنسدلة',
      'de': 'Bitte wählen Sie eine Option aus der Dropdown-Liste aus',
      'es': 'Por favor elija una opción del menú desplegable',
      'fr': 'Veuillez choisir une option dans la liste déroulante',
      'hi': 'कृपया ड्रॉपडाउन से एक विकल्प चुनें',
      'id': 'Silakan pilih opsi dari menu tarik-turun',
      'it': 'Scegli un\'opzione dal menu a discesa',
      'ja': 'ドロップダウンからオプションを選択してください',
      'ko': '드롭다운에서 옵션을 선택하세요.',
      'pt': 'Escolha uma opção no menu suspenso',
      'ru': 'Пожалуйста, выберите вариант из раскрывающегося списка',
      'te': 'దయచేసి డ్రాప్‌డౌన్ నుండి ఒక ఎంపికను ఎంచుకోండి',
      'th': 'โปรดเลือกตัวเลือกจากเมนูแบบเลื่อนลง',
      'tr': 'Lütfen açılır menüden bir seçenek seçin',
      'vi': 'Vui lòng chọn một tùy chọn từ danh sách thả xuống',
      'zh_Hans': '请从下拉列表中选择一个选项',
    },
    '8ccu08a0': {
      'en': 'Create Notes',
      'ar': 'إنشاء ملاحظات',
      'de': 'Erstellen Sie Notizen',
      'es': 'Crear notas',
      'fr': 'Créer des notes',
      'hi': 'नोट्स बनाएं',
      'id': 'Buat Catatan',
      'it': 'Crea note',
      'ja': 'メモの作成',
      'ko': '메모 작성',
      'pt': 'Criar notas',
      'ru': 'Создание заметок',
      'te': 'గమనికలను సృష్టించండి',
      'th': 'สร้างบันทึก',
      'tr': 'Not Oluştur',
      'vi': 'Tạo ghi chú',
      'zh_Hans': '创建笔记',
    },
    'h3p3trq9': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'id': 'Rumah',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'pt': 'Lar',
      'ru': 'Дом',
      'te': 'హోమ్',
      'th': 'บ้าน',
      'tr': 'Ev',
      'vi': 'Trang chủ',
      'zh_Hans': '家',
    },
  },
  // InspectPage
  {
    'xk5yfle8': {
      'en': 'Delete',
      'ar': 'يمسح',
      'de': 'Löschen',
      'es': 'Borrar',
      'fr': 'Supprimer',
      'hi': 'मिटाना',
      'id': 'Menghapus',
      'it': 'Eliminare',
      'ja': '消去',
      'ko': '삭제',
      'pt': 'Excluir',
      'ru': 'Удалить',
      'te': 'తొలగించు',
      'th': 'ลบ',
      'tr': 'Silmek',
      'vi': 'Xóa bỏ',
      'zh_Hans': '删除',
    },
  },
  // auth_WelcomeScreen
  {
    'fuboq56x': {
      'en': 'Personalized Habits Tracker',
      'ar': 'تعقب العادات الشخصية',
      'de': 'Personalisierter Gewohnheits-Tracker',
      'es': 'Rastreador de hábitos personalizado',
      'fr': 'Suivi des habitudes personnalisé',
      'hi': 'वैयक्तिकृत आदतें ट्रैकर',
      'id': 'Pelacak Kebiasaan yang Dipersonalisasi',
      'it': 'Tracker personalizzato delle abitudini',
      'ja': 'パーソナライズされた習慣トラッカー',
      'ko': '개인화된 습관 추적기',
      'pt': 'Rastreador de hábitos personalizados',
      'ru': 'Персонализированный трекер привычек',
      'te': 'వ్యక్తిగతీకరించిన అలవాట్ల ట్రాకర్',
      'th': 'ตัวติดตามนิสัยส่วนบุคคล',
      'tr': 'Kişiselleştirilmiş Alışkanlıklar Takibi',
      'vi': 'Trình theo dõi thói quen cá nhân',
      'zh_Hans': '个性化习惯追踪器',
    },
    '9ziyx56n': {
      'en': 'A user-friendly application for tracking daily habits ',
      'ar': 'تطبيق سهل الاستخدام لتتبع العادات اليومية',
      'de':
          'Eine benutzerfreundliche Anwendung zur Verfolgung täglicher Gewohnheiten',
      'es': 'Una aplicación fácil de usar para rastrear hábitos diarios',
      'fr': 'Une application conviviale pour suivre les habitudes quotidiennes',
      'hi': 'दैनिक आदतों पर नज़र रखने के लिए एक उपयोगकर्ता-अनुकूल एप्लिकेशन',
      'id': 'Aplikasi yang mudah digunakan untuk melacak kebiasaan sehari-hari',
      'it': 'Un\'applicazione intuitiva per monitorare le abitudini quotidiane',
      'ja': '毎日の習慣を追跡するためのユーザーフレンドリーなアプリケーション',
      'ko': '일상 습관을 추적하기 위한 사용자 친화적인 애플리케이션',
      'pt': 'Um aplicativo fácil de usar para monitorar hábitos diários',
      'ru': 'Удобное приложение для отслеживания повседневных привычек',
      'te':
          'రోజువారీ అలవాట్లను ట్రాక్ చేయడానికి వినియోగదారు-స్నేహపూర్వక అప్లికేషన్',
      'th': 'แอปพลิเคชั่นที่ใช้งานง่ายสำหรับติดตามพฤติกรรมประจำวัน',
      'tr':
          'Günlük alışkanlıkları takip etmek için kullanıcı dostu bir uygulama',
      'vi':
          'Một ứng dụng thân thiện với người dùng để theo dõi thói quen hàng ngày',
      'zh_Hans': '一个用户友好的应用程序，用于跟踪日常习惯',
    },
    '3mlgpn4y': {
      'en': 'Custom Remainders',
      'ar': 'بقايا مخصصة',
      'de': 'Benutzerdefinierte Restbestände',
      'es': 'Restos personalizados',
      'fr': 'Restes personnalisés',
      'hi': 'कस्टम अवशेष',
      'id': 'Sisa Khusus',
      'it': 'Resti personalizzati',
      'ja': 'カスタム剰余',
      'ko': '사용자 정의 나머지',
      'pt': 'Restos personalizados',
      'ru': 'Пользовательские остатки',
      'te': 'కస్టమ్ రిమైండర్లు',
      'th': 'ส่วนที่เหลือที่กำหนดเอง',
      'tr': 'Özel Kalanlar',
      'vi': 'Phần còn lại tùy chỉnh',
      'zh_Hans': '自定义余数',
    },
    'yx2fc802': {
      'en': ' Manage remainders efficiently.',
      'ar': 'إدارة البقايا بكفاءة.',
      'de': 'Restbestände effizient verwalten.',
      'es': 'Gestione los restos de forma eficiente.',
      'fr': 'Gérez efficacement les restes.',
      'hi': 'शेषफलों को कुशलतापूर्वक प्रबंधित करें.',
      'id': 'Kelola sisanya secara efisien.',
      'it': 'Gestisci i residui in modo efficiente.',
      'ja': '残りを効率的に管理します。',
      'ko': '남은 잔액을 효율적으로 관리하세요.',
      'pt': 'Gerencie os restos com eficiência.',
      'ru': 'Эффективно управляйте остатками.',
      'te': 'మిగిలిన వాటిని సమర్ధవంతంగా నిర్వహించండి.',
      'th': 'จัดการส่วนที่เหลืออย่างมีประสิทธิภาพ',
      'tr': 'Kalanları verimli bir şekilde yönetin.',
      'vi': 'Quản lý phần còn lại một cách hiệu quả.',
      'zh_Hans': '有效管理剩余物。',
    },
    '078ng5ms': {
      'en': 'Login',
      'ar': 'تسجيل الدخول',
      'de': 'Anmeldung',
      'es': 'Acceso',
      'fr': 'Se connecter',
      'hi': 'लॉग इन करें',
      'id': 'Gabung',
      'it': 'Login',
      'ja': 'ログイン',
      'ko': '로그인',
      'pt': 'Conecte-se',
      'ru': 'Авторизоваться',
      'te': 'ప్రవేశించండి',
      'th': 'เข้าสู่ระบบ',
      'tr': 'Giriş yapmak',
      'vi': 'Đăng nhập',
      'zh_Hans': '登录',
    },
    'q5j953d0': {
      'en': 'Create an Account',
      'ar': 'إنشاء حساب',
      'de': 'Ein Konto erstellen',
      'es': 'Crea una cuenta',
      'fr': 'Créer un compte',
      'hi': 'खाता बनाएं',
      'id': 'Buat sebuah akun',
      'it': 'Creare un account',
      'ja': 'アカウントを作成する',
      'ko': '계정 만들기',
      'pt': 'Crie a sua conta aqui',
      'ru': 'Завести аккаунт',
      'te': 'ఒక ఎకౌంటు సృష్టించు',
      'th': 'สร้างบัญชี',
      'tr': 'Bir hesap oluşturun',
      'vi': 'Tạo một tài khoản',
      'zh_Hans': '创建一个帐户',
    },
    'jjqs8w3l': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'id': 'Rumah',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'pt': 'Lar',
      'ru': 'Дом',
      'te': 'హోమ్',
      'th': 'บ้าน',
      'tr': 'Ev',
      'vi': 'Trang chủ',
      'zh_Hans': '家',
    },
  },
  // auth_Create
  {
    '50xmr3dv': {
      'en': 'Welcome to our application!',
      'ar': 'مرحبا بكم في تطبيقنا!',
      'de': 'Willkommen zu unserer Bewerbung!',
      'es': '¡Bienvenido a nuestra aplicación!',
      'fr': 'Bienvenue sur notre application !',
      'hi': 'हमारे आवेदन में आपका स्वागत है!',
      'id': 'Selamat datang di aplikasi kami!',
      'it': 'Benvenuti nella nostra applicazione!',
      'ja': '私たちのアプリケーションへようこそ!',
      'ko': '우리의 응용 프로그램에 오신 것을 환영합니다!',
      'pt': 'Bem-vindo ao nosso aplicativo!',
      'ru': 'Добро пожаловать в наше приложение!',
      'te': 'మా దరఖాస్తుకు స్వాగతం!',
      'th': 'ยินดีต้อนรับสู่ใบสมัครของเรา!',
      'tr': 'Uygulamamıza hoş geldiniz!',
      'vi': 'Chào mừng bạn đến với ứng dụng của chúng tôi!',
      'zh_Hans': '欢迎来到我们的应用程序！',
    },
    'a0tup2om': {
      'en': 'Track Daily Habits to be Remaindered.',
      'ar': 'تتبع العادات اليومية التي يجب الحفاظ عليها.',
      'de':
          'Verfolgen Sie tägliche Gewohnheiten, die beibehalten werden sollen.',
      'es':
          'Realice un seguimiento de los hábitos diarios que deben mantenerse.',
      'fr': 'Suivez les habitudes quotidiennes à conserver.',
      'hi': 'शेष रहने के लिए दैनिक आदतों पर नज़र रखें।',
      'id': 'Lacak Kebiasaan Sehari-hari untuk Diingat.',
      'it': 'Tieni traccia delle abitudini quotidiane da mantenere.',
      'ja': '残すべき毎日の習慣を追跡します。',
      'ko': '유지해야 할 일일 습관을 추적하세요.',
      'pt': 'Acompanhe os hábitos diários a serem mantidos.',
      'ru': 'Отслеживайте ежедневные привычки, которые следует запомнить.',
      'te': 'రిమైండర్ చేయవలసిన రోజువారీ అలవాట్లను ట్రాక్ చేయండి.',
      'th': 'ติดตามนิสัยประจำวันให้คงอยู่',
      'tr': 'Kalan Günlük Alışkanlıkları Takip Edin.',
      'vi': 'Theo dõi các thói quen hàng ngày cần được duy trì.',
      'zh_Hans': '跟踪要保留的日常习惯。',
    },
    '7ktrpoe1': {
      'en': 'Display Name',
      'ar': 'اسم العرض',
      'de': 'Anzeigename',
      'es': 'Nombre para mostrar',
      'fr': 'Afficher un nom',
      'hi': 'प्रदर्शित होने वाला नाम',
      'id': 'Nama tampilan',
      'it': 'Nome da visualizzare',
      'ja': '表示名',
      'ko': '이름 표시하기',
      'pt': 'Nome de exibição',
      'ru': 'Отображаемое имя',
      'te': 'ప్రదర్శన పేరు',
      'th': 'ชื่อที่แสดง',
      'tr': 'Ekran adı',
      'vi': 'Tên hiển thị',
      'zh_Hans': '显示名称',
    },
    'w933on34': {
      'en': 'Email Address',
      'ar': 'عنوان البريد الإلكتروني',
      'de': 'E-Mail-Adresse',
      'es': 'Dirección de correo electrónico',
      'fr': 'Adresse e-mail',
      'hi': 'मेल पता',
      'id': 'Alamat email',
      'it': 'Indirizzo e-mail',
      'ja': '電子メールアドレス',
      'ko': '이메일 주소',
      'pt': 'Endereço de email',
      'ru': 'Адрес электронной почты',
      'te': 'ఇమెయిల్ చిరునామా',
      'th': 'ที่อยู่อีเมล',
      'tr': 'E-posta Adresi',
      'vi': 'Địa chỉ email',
      'zh_Hans': '电子邮件地址',
    },
    'iju0rskt': {
      'en': 'Password',
      'ar': 'كلمة المرور',
      'de': 'Passwort',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'hi': 'पासवर्ड',
      'id': 'Kata sandi',
      'it': 'Parola d\'ordine',
      'ja': 'パスワード',
      'ko': '비밀번호',
      'pt': 'Senha',
      'ru': 'Пароль',
      'te': 'పాస్వర్డ్',
      'th': 'รหัสผ่าน',
      'tr': 'Şifre',
      'vi': 'Mật khẩu',
      'zh_Hans': '密码',
    },
    '4ied26gt': {
      'en': 'Create Account',
      'ar': 'إنشاء حساب',
      'de': 'Benutzerkonto erstellen',
      'es': 'Crear una cuenta',
      'fr': 'Créer un compte',
      'hi': 'खाता बनाएं',
      'id': 'Buat Akun',
      'it': 'Creare un account',
      'ja': 'アカウントを作成する',
      'ko': '계정 만들기',
      'pt': 'Criar uma conta',
      'ru': 'Зарегистрироваться',
      'te': 'ఖాతాను సృష్టించండి',
      'th': 'สร้างบัญชี',
      'tr': 'Hesap oluşturmak',
      'vi': 'Tạo tài khoản',
      'zh_Hans': '创建账户',
    },
    'l9ph67b2': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'id': 'Rumah',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'pt': 'Lar',
      'ru': 'Дом',
      'te': 'హోమ్',
      'th': 'บ้าน',
      'tr': 'Ev',
      'vi': 'Trang chủ',
      'zh_Hans': '家',
    },
  },
  // auth_Login
  {
    '5hdf3b42': {
      'en': 'Get to my account',
      'ar': 'الوصول إلى حسابي',
      'de': 'Gehen Sie zu meinem Konto',
      'es': 'llegar a mi cuenta',
      'fr': 'Accéder à mon compte',
      'hi': 'मेरे खाते में जाओ',
      'id': 'Masuk ke akun saya',
      'it': 'Accedi al mio account',
      'ja': '私のアカウントにアクセスしてください',
      'ko': '내 계정으로 이동',
      'pt': 'Acesse minha conta',
      'ru': 'Зайдите в мой аккаунт',
      'te': 'నా ఖాతాలోకి వెళ్లండి',
      'th': 'ไปที่บัญชีของฉัน',
      'tr': 'Hesabıma git',
      'vi': 'Truy cập vào tài khoản của tôi',
      'zh_Hans': '进入我的帐户',
    },
    'chnyb69z': {
      'en': 'Access your wonderful things by logging in below.',
      'ar': 'الوصول إلى الأشياء الرائعة الخاصة بك عن طريق تسجيل الدخول أدناه.',
      'de':
          'Greifen Sie auf Ihre wunderbaren Dinge zu, indem Sie sich unten anmelden.',
      'es': 'Accede a tus cosas maravillosas iniciando sesión a continuación.',
      'fr': 'Accédez à vos merveilles en vous connectant ci-dessous.',
      'hi': 'नीचे लॉग इन करके अपनी अद्भुत चीज़ों तक पहुँचें।',
      'id': 'Akses hal-hal menakjubkan Anda dengan masuk di bawah.',
      'it': 'Accedi alle tue cose meravigliose accedendo di seguito.',
      'ja': '以下にログインして、あなたの素晴らしいものにアクセスしてください。',
      'ko': '아래에 로그인하여 멋진 것들에 액세스하세요.',
      'pt': 'Acesse suas coisas maravilhosas fazendo login abaixo.',
      'ru':
          'Получите доступ к своим замечательным вещам, войдя в систему ниже.',
      'te': 'దిగువన లాగిన్ చేయడం ద్వారా మీ అద్భుతమైన విషయాలను యాక్సెస్ చేయండి.',
      'th': 'เข้าถึงสิ่งมหัศจรรย์ของคุณโดยเข้าสู่ระบบด้านล่าง',
      'tr': 'Aşağıdan giriş yaparak harika şeylerinize erişin.',
      'vi':
          'Truy cập những điều tuyệt vời của bạn bằng cách đăng nhập bên dưới.',
      'zh_Hans': '通过下面的登录来访问您的精彩内容。',
    },
    '7c4p3333': {
      'en': 'Email Address',
      'ar': 'عنوان البريد الإلكتروني',
      'de': 'E-Mail-Adresse',
      'es': 'Dirección de correo electrónico',
      'fr': 'Adresse e-mail',
      'hi': 'मेल पता',
      'id': 'Alamat email',
      'it': 'Indirizzo e-mail',
      'ja': '電子メールアドレス',
      'ko': '이메일 주소',
      'pt': 'Endereço de email',
      'ru': 'Адрес электронной почты',
      'te': 'ఇమెయిల్ చిరునామా',
      'th': 'ที่อยู่อีเมล',
      'tr': 'E-posta Adresi',
      'vi': 'Địa chỉ email',
      'zh_Hans': '电子邮件地址',
    },
    'ded9hzf4': {
      'en': 'Password',
      'ar': 'كلمة المرور',
      'de': 'Passwort',
      'es': 'Contraseña',
      'fr': 'Mot de passe',
      'hi': 'पासवर्ड',
      'id': 'Kata sandi',
      'it': 'Parola d\'ordine',
      'ja': 'パスワード',
      'ko': '비밀번호',
      'pt': 'Senha',
      'ru': 'Пароль',
      'te': 'పాస్వర్డ్',
      'th': 'รหัสผ่าน',
      'tr': 'Şifre',
      'vi': 'Mật khẩu',
      'zh_Hans': '密码',
    },
    'k3l9de1t': {
      'en': 'Forgot Password?',
      'ar': 'هل نسيت كلمة السر؟',
      'de': 'Passwort vergessen?',
      'es': '¿Has olvidado tu contraseña?',
      'fr': 'Mot de passe oublié?',
      'hi': 'पासवर्ड भूल गए?',
      'id': 'Tidak ingat kata sandi?',
      'it': 'Ha dimenticato la password?',
      'ja': 'パスワードをお忘れですか？',
      'ko': '비밀번호를 잊으 셨나요?',
      'pt': 'Esqueceu sua senha?',
      'ru': 'Забыли пароль?',
      'te': 'పాస్‌వర్డ్ మర్చిపోయారా?',
      'th': 'ลืมรหัสผ่าน?',
      'tr': 'Parolanızı mı unuttunuz?',
      'vi': 'Quên mật khẩu?',
      'zh_Hans': '忘记密码？',
    },
    'sqhvxorp': {
      'en': 'Login',
      'ar': 'تسجيل الدخول',
      'de': 'Anmeldung',
      'es': 'Acceso',
      'fr': 'Se connecter',
      'hi': 'लॉग इन करें',
      'id': 'Gabung',
      'it': 'Login',
      'ja': 'ログイン',
      'ko': '로그인',
      'pt': 'Conecte-se',
      'ru': 'Авторизоваться',
      'te': 'ప్రవేశించండి',
      'th': 'เข้าสู่ระบบ',
      'tr': 'Giriş yapmak',
      'vi': 'Đăng nhập',
      'zh_Hans': '登录',
    },
    '56i1t86c': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'id': 'Rumah',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'pt': 'Lar',
      'ru': 'Дом',
      'te': 'హోమ్',
      'th': 'บ้าน',
      'tr': 'Ev',
      'vi': 'Trang chủ',
      'zh_Hans': '家',
    },
  },
  // auth_ForgotPassword
  {
    'o6gikknj': {
      'en': 'Forgot Password',
      'ar': 'هل نسيت كلمة السر',
      'de': 'Passwort vergessen',
      'es': 'Has olvidado tu contraseña',
      'fr': 'Mot de passe oublié',
      'hi': 'पासवर्ड भूल गए',
      'id': 'Tidak ingat kata sandi',
      'it': 'Ha dimenticato la password',
      'ja': 'パスワードをお忘れですか',
      'ko': '비밀번호를 잊으 셨나요',
      'pt': 'Esqueceu sua senha',
      'ru': 'Забыли пароль',
      'te': 'పాస్‌వర్డ్ మర్చిపోయాను',
      'th': 'ลืมรหัสผ่าน',
      'tr': 'Parolanızı mı unuttunuz',
      'vi': 'Quên mật khẩu',
      'zh_Hans': '忘记密码',
    },
    'oofgudf5': {
      'en': 'We will send you a reset link.',
      'ar': 'سوف نرسل لك رابط إعادة التعيين.',
      'de': 'Wir senden Ihnen einen Reset-Link.',
      'es': 'Le enviaremos un enlace de reinicio.',
      'fr': 'Nous vous enverrons un lien de réinitialisation.',
      'hi': 'हम आपको एक रीसेट लिंक भेजेंगे.',
      'id': 'Kami akan mengirimkan Anda tautan reset.',
      'it': 'Ti invieremo un collegamento per il ripristino.',
      'ja': 'リセットリンクをお送りします。',
      'ko': '재설정 링크를 보내드리겠습니다.',
      'pt': 'Enviaremos um link de redefinição.',
      'ru': 'Мы вышлем вам ссылку для сброса.',
      'te': 'మేము మీకు రీసెట్ లింక్‌ని పంపుతాము.',
      'th': 'เราจะส่งลิงค์รีเซ็ตไปให้คุณ',
      'tr': 'Size bir sıfırlama bağlantısı göndereceğiz.',
      'vi': 'Chúng tôi sẽ gửi cho bạn một liên kết thiết lập lại.',
      'zh_Hans': '我们将向您发送重置链接。',
    },
    'vpbj2g0v': {
      'en': 'Email Address',
      'ar': 'عنوان البريد الإلكتروني',
      'de': 'E-Mail-Adresse',
      'es': 'Dirección de correo electrónico',
      'fr': 'Adresse e-mail',
      'hi': 'मेल पता',
      'id': 'Alamat email',
      'it': 'Indirizzo e-mail',
      'ja': '電子メールアドレス',
      'ko': '이메일 주소',
      'pt': 'Endereço de email',
      'ru': 'Адрес электронной почты',
      'te': 'ఇమెయిల్ చిరునామా',
      'th': 'ที่อยู่อีเมล',
      'tr': 'E-posta Adresi',
      'vi': 'Địa chỉ email',
      'zh_Hans': '电子邮件地址',
    },
    '63tp1la0': {
      'en': 'Send Link',
      'ar': 'أرسل الرابط',
      'de': 'Link senden',
      'es': 'Enviar enlace',
      'fr': 'Envoyer un lien',
      'hi': 'लिंक भेजें',
      'id': 'Kirim Tautan',
      'it': 'Invia il link',
      'ja': 'リンクを送る',
      'ko': '링크 보내기',
      'pt': 'Enviar Link',
      'ru': 'Отправить ссылку',
      'te': 'లింక్ పంపండి',
      'th': 'ส่งลิ้งค์',
      'tr': 'Link gönder',
      'vi': 'Gửi link',
      'zh_Hans': '发送链接',
    },
    'hj5vrz2h': {
      'en': 'Home',
      'ar': 'بيت',
      'de': 'Heim',
      'es': 'Hogar',
      'fr': 'Maison',
      'hi': 'घर',
      'id': 'Rumah',
      'it': 'Casa',
      'ja': '家',
      'ko': '집',
      'pt': 'Lar',
      'ru': 'Дом',
      'te': 'హోమ్',
      'th': 'บ้าน',
      'tr': 'Ev',
      'vi': 'Trang chủ',
      'zh_Hans': '家',
    },
  },
  // Adspage
  {
    'nonehlp0': {
      'en': 'Wait For 10 Seconds',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'uy5ttdp8': {
      'en': 'Go Back',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'zvwvukcn': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
  },
  // DonationPage
  {
    'l00vjvl1': {
      'en': 'Google Pay',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'axfrc6w1': {
      'en': 'Scan to Donate',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'ngtuqhg9': {
      'en': 'Button',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'anhe9apd': {
      'en': 'PayPal',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'ybchd7ju': {
      'en': 'Click Here',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'wp4e1t4q': {
      'en': 'Donate Now',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'pvc6qedr': {
      'en': 'Home',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
  },
  // Miscellaneous
  {
    'hn2rkb9q': {
      'en': 'Give this permission',
      'ar': 'أعط هذا الإذن',
      'de': 'Erteilen Sie diese Erlaubnis',
      'es': 'Dar este permiso',
      'fr': 'Donnez cette autorisation',
      'hi': 'यह अनुमति दीजिये',
      'id': 'Berikan izin ini',
      'it': 'Dai questo permesso',
      'ja': 'この許可を与える',
      'ko': '이 권한을 부여하세요',
      'pt': 'Dê esta permissão',
      'ru': 'Дайте это разрешение',
      'te': 'ఈ అనుమతి ఇవ్వండి',
      'th': 'ให้อนุญาตนี้',
      'tr': 'Bu izni ver',
      'vi': 'Cấp quyền này',
      'zh_Hans': '授予此权限',
    },
    'wxa2u0io': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'oae0k5nm': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'falc98va': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'zdsihvvx': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'b867aijy': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '8zzg95u1': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'tftvxluv': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'wp4vrvhn': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '16v5n061': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '0tw2u17i': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'kq93z6f3': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '0nv6xuom': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'ut8xqh08': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'wgkmq592': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'v4mg9sdr': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'wcmdifth': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'e3s49nwm': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'cqdhfo80': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'wk1474kd': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'qsxw72vw': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'ncvpzqt5': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'lvs44r0j': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'ektot6nm': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    '7m4c99wi': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
    'brx44ttt': {
      'en': '',
      'ar': '',
      'de': '',
      'es': '',
      'fr': '',
      'hi': '',
      'id': '',
      'it': '',
      'ja': '',
      'ko': '',
      'pt': '',
      'ru': '',
      'te': '',
      'th': '',
      'tr': '',
      'vi': '',
      'zh_Hans': '',
    },
  },
].reduce((a, b) => a..addAll(b));
